### ISSUE TITLE
Redundant dimensions

### ISSUE THREAD

**Issue by Msturroc** [ayoublasri/Biomodelling.jl#3]
There seem to be redundant dimensions in the storage variables. X = zeros(K,1) => zeros(K)
etc.

**Comment by ppalmes** [comment]
zeros(K) has Array{Float64,1} type which is a vector. zeros(K,1) has Array{Float64,2} type which is a Matrix. 

Julia> typeof(zeros(10,1)) <: Matrix
Julia> true
Julia>  typeof(zeros(10)) <: Vector
Julia> true

depending in usage, you may need to decide whether you are using vector or matrix. the difference was i think introduce in julia 1.0 because it used to be that when you transpose a vector in julia, it becomes a matrix because it did not maintain the 1-dimensionality of vector.

https://stackoverflow.com/questions/21152051/difference-between-nx1-array-and-n-element-array-in-julia

**Comment by Msturroc** [comment]
Thanks for this insight Paulito.
